// <auto-generated />
using System;
using LabAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LabAPI.Migrations
{
    [DbContext(typeof(LabApiContext))]
    [Migration("20230421185852_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LabAPI.Models.Enfermeiro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("COFEN_UF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("COFEN/UF");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CPF");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATA_NASCIMENTO");

                    b.Property<string>("Genero")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("GENERO");

                    b.Property<string>("InstituicaoEnsinoFormacao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("INSTITUIÇÃO_ENSINO_FORMACAO");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NOME_COMPLETO");

                    b.Property<string>("Telefone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("TELEFONE");

                    b.HasKey("Id");

                    b.ToTable("ENFERMEIROS");

                    b.HasData(
                        new
                        {
                            Id = 3,
                            COFEN_UF = "186.566/SC",
                            CPF = "132.147.698-20",
                            DataNascimento = new DateTime(1989, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = "Masculino",
                            InstituicaoEnsinoFormacao = "UFSC",
                            NomeCompleto = "Mateus Raimundo Aragão",
                            Telefone = "48999251200"
                        },
                        new
                        {
                            Id = 4,
                            COFEN_UF = "162.780/SC",
                            CPF = "825.497.397-01",
                            DataNascimento = new DateTime(1990, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = "Feminino",
                            InstituicaoEnsinoFormacao = "UDESC",
                            NomeCompleto = "Sarah Isabelle",
                            Telefone = "48991002564"
                        });
                });

            modelBuilder.Entity("LabAPI.Models.Medico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CPF");

                    b.Property<string>("CRM_UF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CRM/UF");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATA_NASCIMENTO");

                    b.Property<int>("Especializacao_Clinica")
                        .HasColumnType("int")
                        .HasColumnName("ESPECIALIZACAO_CLINICA");

                    b.Property<int>("Estado_No_Sistema")
                        .HasColumnType("int")
                        .HasColumnName("ESTADO_NO_SISTEMA");

                    b.Property<string>("Genero")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("GENERO");

                    b.Property<string>("InstituicaoEnsinoFormacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("INSTITUIÇÃO_ENSINO_FORMACAO");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NOME_COMPLETO");

                    b.Property<string>("Telefone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("TELEFONE");

                    b.Property<int>("TotalAtendimentos")
                        .HasColumnType("int")
                        .HasColumnName("TOTAL_ATENDIMENTOS");

                    b.HasKey("Id");

                    b.ToTable("MEDICOS");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CPF = "140.159.530-14",
                            CRM_UF = "215.630/RJ",
                            DataNascimento = new DateTime(1989, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Especializacao_Clinica = 1,
                            Estado_No_Sistema = 1,
                            Genero = "Feminino",
                            InstituicaoEnsinoFormacao = "URJ",
                            NomeCompleto = "Julia Vitória Barros",
                            Telefone = "48999201511",
                            TotalAtendimentos = 0
                        },
                        new
                        {
                            Id = 2,
                            CPF = "198.230.852-99",
                            CRM_UF = "125.541/SC",
                            DataNascimento = new DateTime(1989, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Especializacao_Clinica = 5,
                            Estado_No_Sistema = 1,
                            Genero = "Masculino",
                            InstituicaoEnsinoFormacao = "UDESC",
                            NomeCompleto = "Lorenzo Benedito Monteiro",
                            Telefone = "48992015021",
                            TotalAtendimentos = 0
                        });
                });

            modelBuilder.Entity("LabAPI.Models.Paciente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Alergias")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ALERGIAS");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CPF");

                    b.Property<string>("ContatoEmergencia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CONTATO_EMERGENCIA");

                    b.Property<string>("Convenio")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("CONVENIO");

                    b.Property<string>("CuidadosEspecificos")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CUIDADOS_ESPECIAIS");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATA_NASCIMENTO");

                    b.Property<string>("Genero")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("GENERO");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NOME_COMPLETO");

                    b.Property<string>("Telefone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("TELEFONE");

                    b.Property<int>("TotalAtendimentos")
                        .HasColumnType("int")
                        .HasColumnName("TOTAL_ATENDIMENTOS");

                    b.Property<int>("statusAtendimento")
                        .HasColumnType("int")
                        .HasColumnName("STATUS_ATENDIMENTO");

                    b.HasKey("Id");

                    b.ToTable("PACIENTES");

                    b.HasData(
                        new
                        {
                            Id = 5,
                            Alergias = "Rinite",
                            CPF = "523.252.349-08",
                            ContatoEmergencia = "4833259547",
                            Convenio = "Bradesco Saude",
                            CuidadosEspecificos = "não possui",
                            DataNascimento = new DateTime(1980, 11, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = "Masculino",
                            NomeCompleto = "Alexandre Lorenzo da Mota",
                            Telefone = "4828454720",
                            TotalAtendimentos = 0,
                            statusAtendimento = 0
                        },
                        new
                        {
                            Id = 6,
                            Alergias = "Asma Bronquica",
                            CPF = "142.154.935-28",
                            ContatoEmergencia = "4899631200",
                            Convenio = "One Health",
                            CuidadosEspecificos = "faz uso regular da bombinha",
                            DataNascimento = new DateTime(1996, 7, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = "Feminino",
                            NomeCompleto = "Gabrielly Vitória Sueli Lopes",
                            Telefone = "4830459633",
                            TotalAtendimentos = 0,
                            statusAtendimento = 0
                        },
                        new
                        {
                            Id = 7,
                            Alergias = "Leite e derivados",
                            CPF = "670.534.738-48",
                            ContatoEmergencia = "4836210056",
                            Convenio = "Unimed",
                            CuidadosEspecificos = "faz reposição de hormonios",
                            DataNascimento = new DateTime(1975, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = "Feminino",
                            NomeCompleto = "Aurora Francisca Marcela Bernardes",
                            Telefone = "4833254796",
                            TotalAtendimentos = 0,
                            statusAtendimento = 0
                        },
                        new
                        {
                            Id = 8,
                            Alergias = "Frutos do Mar",
                            CPF = "709.924.665-80",
                            ContatoEmergencia = "4833002100",
                            Convenio = "One Health",
                            CuidadosEspecificos = "não possui",
                            DataNascimento = new DateTime(1969, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = "Masculino",
                            NomeCompleto = "Manoel Renato Theo da Cunha",
                            Telefone = "4891224420",
                            TotalAtendimentos = 0,
                            statusAtendimento = 0
                        },
                        new
                        {
                            Id = 9,
                            Alergias = "Não possui",
                            CPF = "253.415.630-69",
                            ContatoEmergencia = "4833256612",
                            Convenio = "Unimed",
                            CuidadosEspecificos = "não possui",
                            DataNascimento = new DateTime(1991, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = "Feminino",
                            NomeCompleto = "Bruna Rosângela Francisca",
                            Telefone = "4899951120",
                            TotalAtendimentos = 0,
                            statusAtendimento = 0
                        },
                        new
                        {
                            Id = 10,
                            Alergias = "Urticária",
                            CPF = "506.250.120-44",
                            ContatoEmergencia = "4830459992",
                            Convenio = "Bradesco Saude",
                            CuidadosEspecificos = "não possui",
                            DataNascimento = new DateTime(1993, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = "Masculino",
                            NomeCompleto = "Luiz Gustavo Costa",
                            Telefone = "4899220000",
                            TotalAtendimentos = 0,
                            statusAtendimento = 0
                        },
                        new
                        {
                            Id = 11,
                            Alergias = "Rinite, Bronquite, Camarão",
                            CPF = "513.327.137-93",
                            ContatoEmergencia = "48999520021",
                            Convenio = "SulAmérica Saude",
                            CuidadosEspecificos = "não possui",
                            DataNascimento = new DateTime(1989, 9, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = "Feminino",
                            NomeCompleto = "Mariana Daniela Aragão",
                            Telefone = "4833090054",
                            TotalAtendimentos = 0,
                            statusAtendimento = 0
                        },
                        new
                        {
                            Id = 12,
                            Alergias = "Não possui",
                            CPF = "922.265.830-25",
                            ContatoEmergencia = "4833149951",
                            Convenio = "Bradesco Saude",
                            CuidadosEspecificos = "não possui",
                            DataNascimento = new DateTime(1972, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = "Feminino",
                            NomeCompleto = "Emanuelly Regina",
                            Telefone = "48999195520",
                            TotalAtendimentos = 0,
                            statusAtendimento = 0
                        },
                        new
                        {
                            Id = 13,
                            Alergias = "Alergia a Niquel",
                            CPF = "867.882.944-37",
                            ContatoEmergencia = "4833133021",
                            Convenio = "One Health",
                            CuidadosEspecificos = "não possui",
                            DataNascimento = new DateTime(1969, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = "Feminino",
                            NomeCompleto = "Jennifer Vanessa Marlene Peixoto",
                            Telefone = "48999000015",
                            TotalAtendimentos = 0,
                            statusAtendimento = 0
                        },
                        new
                        {
                            Id = 14,
                            Alergias = "Camarão",
                            CPF = "750.120.356-20",
                            ContatoEmergencia = "4830492210",
                            Convenio = "SulAmérica Saude",
                            CuidadosEspecificos = "não possui",
                            DataNascimento = new DateTime(1981, 4, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = "Masculino",
                            NomeCompleto = "Joaquim Leandro Julio Silva",
                            Telefone = "4899101220",
                            TotalAtendimentos = 0,
                            statusAtendimento = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
